version: '3'
services:
  mongodb:
    image: mongo
    container_name: scoobymongodb
    ports:
      - "27017:27017"
    environment:
     - MONGO_INITDB_DATABASE=admin
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./mongod.conf:/etc/mongod.conf
    networks:
      - scoobyapp_net
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scoobyapp
    ports:
      - "8502:8501"
    networks:
      - scoobyapp_net
    depends_on:
      - mongodb

volumes:
  mongodb_data:

networks:
  scoobyapp_net: